name: check

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  flake-check:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix flake check
